# Generated by Django 3.1.7 on 2021-04-03 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('intials', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Central Administration'), (2, 'Campus'), (3, 'Course'), (4, 'Collegiate'), (5, 'Counsel'), (6, 'Organ'), (7, 'Regional'), (8, 'Academic Unit'), (9, 'External Unit')], default=1)),
                ('year', models.IntegerField()),
                ('last_expedition_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminUnitMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_boss', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.IntegerField(choices=[(1, 'Teacher'), (2, 'Intern'), (3, 'Student'), (4, 'Technician')], default=1)),
                ('description', models.TextField()),
                ('admin_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.adminunit')),
            ],
        ),
        migrations.CreateModel(
            name='Ordinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('admin_unit_initials', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('expedition_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_author_of', to='api.adminunitmember')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdinanceMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('reference_type', models.IntegerField()),
                ('occupation_type', models.IntegerField()),
                ('description', models.TextField()),
                ('workload', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.adminunitmember')),
                ('ordinance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ordinance')),
            ],
        ),
        migrations.CreateModel(
            name='OrdinanceCitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Void'), (2, 'Mention'), (3, 'Rectification'), (4, 'Revocation')], default=1)),
                ('description', models.TextField()),
                ('from_ordinance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_ordinance', to='api.ordinance')),
                ('to_ordinance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_ordinance', to='api.ordinance')),
            ],
        ),
        migrations.AddField(
            model_name='ordinance',
            name='citations',
            field=models.ManyToManyField(related_name='_ordinance_citations_+', through='api.OrdinanceCitation', to='api.Ordinance'),
        ),
        migrations.AddField(
            model_name='ordinance',
            name='members_refered',
            field=models.ManyToManyField(through='api.OrdinanceMember', to='api.AdminUnitMember'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('admin_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.adminunit')),
                ('admin_unit_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.adminunitmember')),
                ('ordinance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ordinance')),
            ],
        ),
        migrations.CreateModel(
            name='Directive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Orientation'), (2, 'Rule')], default=1)),
                ('description', models.TextField()),
                ('ordinance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directives', to='api.ordinance')),
                ('previous_directive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.directive')),
            ],
        ),
        migrations.AddField(
            model_name='adminunitmember',
            name='ordinances_received',
            field=models.ManyToManyField(through='api.OrdinanceMember', to='api.Ordinance'),
        ),
        migrations.AddField(
            model_name='adminunitmember',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
        migrations.AddField(
            model_name='adminunit',
            name='last_ordinance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_admin_unit', to='api.ordinance'),
        ),
        migrations.AddField(
            model_name='adminunit',
            name='members',
            field=models.ManyToManyField(through='api.AdminUnitMember', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='adminunit',
            name='ordinances',
            field=models.ManyToManyField(through='api.Notification', to='api.Ordinance'),
        ),
    ]
