# Generated by Django 3.1.7 on 2021-04-03 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminunit',
            name='last_ordinance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_admin_unit', to='api.ordinance'),
        ),
        migrations.AlterField(
            model_name='adminunit',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, through='api.AdminUnitMember', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='adminunit',
            name='ordinances',
            field=models.ManyToManyField(blank=True, null=True, through='api.Notification', to='api.Ordinance'),
        ),
        migrations.AlterField(
            model_name='adminunitmember',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='adminunitmember',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordinance',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_author_of', to='api.adminunitmember'),
        ),
        migrations.AlterField(
            model_name='ordinance',
            name='citations',
            field=models.ManyToManyField(blank=True, null=True, related_name='_ordinance_citations_+', through='api.OrdinanceCitation', to='api.Ordinance'),
        ),
        migrations.AlterField(
            model_name='ordinance',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ordinance',
            name='expedition_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ordinance',
            name='members_refered',
            field=models.ManyToManyField(blank=True, null=True, through='api.OrdinanceMember', to='api.AdminUnitMember'),
        ),
        migrations.AlterField(
            model_name='ordinance',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
