# Generated by Django 3.1.7 on 2021-04-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210403_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminunit',
            name='members',
            field=models.ManyToManyField(through='api.AdminUnitMember', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='adminunit',
            name='ordinances',
            field=models.ManyToManyField(through='api.Notification', to='api.Ordinance'),
        ),
        migrations.AlterField(
            model_name='ordinance',
            name='citations',
            field=models.ManyToManyField(related_name='_ordinance_citations_+', through='api.OrdinanceCitation', to='api.Ordinance'),
        ),
        migrations.AlterField(
            model_name='ordinance',
            name='members_refered',
            field=models.ManyToManyField(through='api.OrdinanceMember', to='api.AdminUnitMember'),
        ),
    ]
