# Generated by Django 3.1.7 on 2021-04-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210404_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordinance',
            name='year',
        ),
        migrations.AddField(
            model_name='ordinance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Proposta'), (2, 'Vigente'), (3, 'Expirada'), (4, 'Anulada'), (5, 'Retificada'), (6, 'Revogada')], default=1),
        ),
    ]
