# Generated by Django 3.1.7 on 2021-04-19 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210405_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminunit',
            old_name='intials',
            new_name='initials',
        ),
        migrations.RemoveField(
            model_name='adminunit',
            name='last_expedition_number',
        ),
    ]
