# Generated by Django 3.1.7 on 2021-04-19 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210419_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordinance',
            old_name='members_refered',
            new_name='members_referred',
        ),
        migrations.RemoveField(
            model_name='adminunit',
            name='last_ordinance',
        ),
        migrations.AddField(
            model_name='ordinance',
            name='admin_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.adminunit'),
        ),
        migrations.AlterField(
            model_name='adminunit',
            name='members',
            field=models.ManyToManyField(through='api.Notification', to='api.AdminUnitMember'),
        ),
    ]
