# Generated by Django 3.1.7 on 2021-04-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210421_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directive',
            name='previous_directive',
        ),
        migrations.AddField(
            model_name='directive',
            name='directive_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
