# Generated by Django 3.1.7 on 2021-04-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210422_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinance',
            name='expedition_year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordinance',
            name='sequential_id',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
