# Generated by Django 3.1.7 on 2021-04-22 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210422_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordinance',
            name='pdf_path',
        ),
    ]
