# Generated by Django 3.1.7 on 2021-05-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210422_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminunit',
            name='year',
        ),
        migrations.AlterField(
            model_name='adminunit',
            name='last_issued_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminunit',
            name='last_proposed_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
